import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//components
import NavBar from './components/NavBar'
import ImageComponent from './components/ImageComponent'
//images
import bike from '../public/images/BiciReal.png'
import group from '../public/images/GrupoReal.svg'
import lupa from '../public/images/lupaReal.png'

export default function Home() {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* EL bootstrap */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
     
        {/* google Font  */}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Montserrat:wght@200;300;400&family=Nunito:ital,wght@0,200;0,400;1,200&family=Roboto:wght@300;400&display=swap" rel="stylesheet"/>
        {/* Fontawesome  ICONS*/}

      </Head>
      
      <main className={styles.main}>
        <NavBar/>
        <div className='position-relative border border-4'>
          <ImageComponent src={'/../public/images/portada.jpg'} alt={'Alterna'}/>
          <h1 id={styles.title}>Decile</h1>
          <h1 id={styles.titleAbajo}>SI a <strong id={styles.strongNameTitle}>Clismo</strong></h1>
        </div>
        <div className='row text-center mt-5'>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={group}
            width={200}
            height={200}
            alt='aversianda'
            />
            <h3 className={styles.legend}>Conecta con tu entrenador</h3>
          </div>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={bike}
            width={200}
            height={200}
            alt='aversianda'
            className={styles.icon}/>
            <h3 className={styles.legend}>Realiza los entrenamientos</h3>
          </div>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={lupa}
            width={200}
            height={200}
            alt='aversianda'
            className={styles.icon}/>
            <h3 className={styles.legend}>Comprueba tu rendimiento</h3>
          </div>
        </div>

      </main>
    </div>
  )
}
