import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//components
import NavBar from './components/NavBar'
import ImageComponent from './components/ImageComponent'
//images
import bike from '../public/images/BiciReal.png'
import group from '../public/images/GrupoReal.svg'
import lupa from '../public/images/lupaReal.png'

export default function Home() {

  
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <NavBar/>
        <div className='position-relative border border-4'>
          <ImageComponent src={'/../public/images/portada.jpg'} alt={'Alterna'}/>
          <h1 id={styles.title}>Decile</h1>
          <h1 id={styles.titleAbajo}>SI a <strong id={styles.strongNameTitle}>Clismo</strong></h1>
        </div>
        <div className='row text-center mt-5'>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={group}
            width={200}
            height={200}
            alt='aversianda'
            />
            <h3 className={styles.legend}>Conecta con tu entrenador</h3>
          </div>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={bike}
            width={200}
            height={200}
            alt='aversianda'
            className={styles.icon}/>
            <h3 className={styles.legend}>Realiza los entrenamientos</h3>
          </div>
          <div className='col-12 col-md-4 col-lg-4 col-sm-12'>
            <Image 
            src={lupa}
            width={200}
            height={200}
            alt='aversianda'
            className={styles.icon}/>
            <h3 className={styles.legend}>Comprueba tu rendimiento</h3>
          </div>
        </div>

      </main>
    </div>
  )
}
